export const ADD_LOGGED_IN_USER = 'ADD_LOGGED_IN_USER';
export const DELETE_LOGGED_IN_USER = 'DELETE_LOGGED_IN_USER';

export const ADD_SELECTED_USER = 'ADD_SELECTED_USER';
export const DELETE_SELECTED_USER = 'DELETE_SELECTED_USER';

export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const ADD_SUBSCRIBTION = 'ADD_SUBSCRIBTION';
export const DELETE_SUBSCRIBTION = 'DELETE_SUBSCRIBTION';

export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
