export const GET_LOGGED_IN_USER = 'GET_LOGGED_IN_USER';
export const ADD_LOGGED_IN_USER = 'ADD_LOGGED_IN_USER';
export const DELETE_LOGGED_IN_USER = 'DELETE_LOGGED_IN_USER';

// export const GET_SELECTED_USER = 'GET_SELECTED_USER';
export const ADD_SELECTED_USER = 'ADD_SELECTED_USER';
export const DELETE_SELECTED_USER = 'DELETE_SELECTED_USER';

export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const GET_SUBSCRIBTIONS = 'GET_SUBSCRIBTIONS';
export const ADD_SUBSCRIBTION = 'ADD_SUBSCRIBTION';
export const DELETE_SUBSCRIBTION = 'DELETE_SUBSCRIBTION';

export const GET_POSTS = 'GET_POSTS';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
